log:
  file:  ./social_network_core.log
name: "social_network_core"
env: "dev"
api:
  port:  4444
  readtimeout: 2000
  writetimeout: 2000
db:
  provider: "mysql"
  address: "localhost"
  port: "3306"
  login: "user"
  password: "userpw"
  name: "networkcore"