log:
  file:  ./social_network_core.log
name: "social_network_core"
env: "dev"
port:  4444
api:
  readtimeout: 2000
  writetimeout: 2000
db:
  provider: "mysql"
  master: "localhost:3306"
  slaves:
    - "localhost:3307"
    - "localhost:3308"
  login: "user"
  password: "userpw"
  name: "networkcore"